// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrafficTestApiClient is the client API for TrafficTestApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrafficTestApiClient interface {
	TrafficRequest(ctx context.Context, in *TrafficTestRequest, opts ...grpc.CallOption) (*TrafficTestResponse, error)
}

type trafficTestApiClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficTestApiClient(cc grpc.ClientConnInterface) TrafficTestApiClient {
	return &trafficTestApiClient{cc}
}

func (c *trafficTestApiClient) TrafficRequest(ctx context.Context, in *TrafficTestRequest, opts ...grpc.CallOption) (*TrafficTestResponse, error) {
	out := new(TrafficTestResponse)
	err := c.cc.Invoke(ctx, "/traffic.api.TrafficTestApi/TrafficRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrafficTestApiServer is the server API for TrafficTestApi service.
// All implementations must embed UnimplementedTrafficTestApiServer
// for forward compatibility
type TrafficTestApiServer interface {
	TrafficRequest(context.Context, *TrafficTestRequest) (*TrafficTestResponse, error)
	mustEmbedUnimplementedTrafficTestApiServer()
}

// UnimplementedTrafficTestApiServer must be embedded to have forward compatible implementations.
type UnimplementedTrafficTestApiServer struct {
}

func (UnimplementedTrafficTestApiServer) TrafficRequest(context.Context, *TrafficTestRequest) (*TrafficTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrafficRequest not implemented")
}
func (UnimplementedTrafficTestApiServer) mustEmbedUnimplementedTrafficTestApiServer() {}

// UnsafeTrafficTestApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficTestApiServer will
// result in compilation errors.
type UnsafeTrafficTestApiServer interface {
	mustEmbedUnimplementedTrafficTestApiServer()
}

func RegisterTrafficTestApiServer(s grpc.ServiceRegistrar, srv TrafficTestApiServer) {
	s.RegisterService(&TrafficTestApi_ServiceDesc, srv)
}

func _TrafficTestApi_TrafficRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrafficTestApiServer).TrafficRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/traffic.api.TrafficTestApi/TrafficRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrafficTestApiServer).TrafficRequest(ctx, req.(*TrafficTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrafficTestApi_ServiceDesc is the grpc.ServiceDesc for TrafficTestApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficTestApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "traffic.api.TrafficTestApi",
	HandlerType: (*TrafficTestApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrafficRequest",
			Handler:    _TrafficTestApi_TrafficRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/helloworld.proto",
}
